#!/bin/bash

# Slackware script to define the 0scripts environment

# Copyright 2026 Antonio Leal, Porto Salvo, Oeiras, Portugal
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

MYNAME="Antonio Leal"
MYEMAIL="antonioleal@yahoo.com"
MYCOPYRIGHT="# Copyright 2026 Antonio Leal, Porto Salvo, Oeiras, Portugal"

YOURSLACKBUILDS_REPO="https://github.com/antonioleal/myslackbuilds"
SLACKBUILDS_REPO="https://github.com/antonioleal/slackbuilds"

#EDITOR="geany -i"
EDITOR="gvim"
ARCHIVER="engrampa"

# When spawning a terminal these options are placed in sequence
TERMINAL="xterm"
TERMINALOPTS="-fa 'Monospace' -fg white -bg black -fs 14 -maximized"
TERMINALHOLD="-hold"
TERMINALRUN="-e"
